name: mservice_app
description: M-Service Client App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_ringtone_player: any
  cupertino_icons: any
  firebase_core: any
  cloud_firestore: any
  shared_preferences: any
  url_launcher: any
  share_plus: any
  firebase_messaging: any
  googleapis_auth: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/firebase_credentials.json
