name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Generate system files
        run: flutter create --platforms=android .
        
      - name: Fix Android Manifest for SMS
        run: |
          echo "import 'dart:io'; void main() { var f = File('android/app/src/main/AndroidManifest.xml'); var text = f.readAsStringSync(); text = text.replaceFirst('<application', '<queries><intent><action android:name=\"android.intent.action.VIEW\"/><data android:scheme=\"sms\"/></intent></queries><application'); f.writeAsStringSync(text); }" > fix_manifest.dart
          dart fix_manifest.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Fix Android SDK versions
        run: |
          find /home/runner/.pub-cache/hosted -name "build.gradle" -type f -exec sed -i 's/compileSdkVersion 33/compileSdkVersion 34/g' {} +
          find /home/runner/.pub-cache/hosted -name "build.gradle" -type f -exec sed -i 's/compileSdk 33/compileSdk 34/g' {} +
          sed -i 's/compileSdk = 33/compileSdk = 34/g' android/app/build.gradle.kts 2>/dev/null || true
          sed -i 's/targetSdk = 33/targetSdk = 34/g' android/app/build.gradle.kts 2>/dev/null || true
          sed -i 's/compileSdkVersion 33/compileSdkVersion 34/g' android/app/build.gradle 2>/dev/null || true
          sed -i 's/targetSdkVersion 33/targetSdkVersion 34/g' android/app/build.gradle 2>/dev/null || true

            # ❗ МАГИЯ БЕЗОПАСНОСТИ: Внедряем ключи из сейфа ❗
      - name: Inject Secret Keys
        run: |
          mkdir -p assets
          cat << 'EOF' > assets/firebase_credentials.json
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          EOF
          mkdir -p android/app
          cat << 'EOF' > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
          
      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
